spring:
  application:
    name: kt-sym

server:
  port: 80
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
          include: "*"

feign:
  client:
    config:
      cartCalculatorClient:
        url: ${KT_SYM_CART_CALCULATOR_URL:localhost:8080}
