spring:
  application:
    name: kt-sym

server:
  port: 80
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
          include: "*"

feign:
  client:
    config:
      cartCalculatorClient:
        url: ${KT_SYM_CART_CALCULATOR_URL:localhost:8080}

kt.sym.cart.body: '[{ "book": {"isbn": "1447264533","author": "Margaret Mitchell","title": "Gone with the Wind","synopsis": null,"language": null }, "links": [{"rel": "self","href": "http://localhost:8081/api/books/1447264533"} ]},{ "book": {"isbn": "0451524934","author": "George Orwell","title": "1984","synopsis": null,"language": null }, "links": [{"rel": "self","href": "http://localhost:8081/api/books/0451524934"} ]}]'